### PR TITLE
Fix #37 allow single zero without leading zeros in prerelease version

### LINKED ISSUE #37: Remove trailing zeros from prelease doesn't allow to parse 0 pre-release version
This was broken by: https://github.com/k-bx/python-semver/commit/69e9125cfe3dc1537163ffbd4fdfe9c09025b686

By standart [semver](http://semver.org/#spec-item-9):

> Numeric identifiers MUST NOT include leading zeroes.

But 0 value doesn't have leading zeros.

**Steps to reproduce:**
Try to parse ```1.0.0-rc.0```

**Actual behavior:**
It fails

**Expected behavior:**
```1.0.0-rc.0``` should be parsed

### PR DESCRIPTION
**Pull request by werwolfby**

### CODE REVIEW

**Comment by werwolfby** [comment]
@k-bx thx, it was fast )

**Comment by k-bx** [comment]
@werwolfby thank you, released under 2.7.2!

**Comment by werwolfby** [comment]
I'm not in the list of contributors :(

**Comment by k-bx** [comment]
@werwolfby sorry about that. Which email should I put?

**Comment by werwolfby** [comment]
@k-bx no problem.
```werwolf.by@gmail.com```

**Pull request merged**
