### PR TITLE
[WIP] Add Python 3.7 support

### PR DESCRIPTION
**Pull request by scls19fr**

### CODE REVIEW

**Comment by scls19fr** [comment]
Travis CI build for Python 3.7 is broken
See https://travis-ci.org/k-bx/python-semver/jobs/439648083

**Comment by ppkt** [comment]
Weird, it looks like it's not supported at all but there is an "official workaround": https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905

**Comment by tomschr** [comment]
@ppkt, @scls19fr 
I think, currently with Travis you use Ubuntu Trusty Tahr (14.04). You can see that in the URL:

```
Setting APT mirror in /etc/apt/sources.list: http://us-east-1.ec2.archive.ubuntu.com/ubuntu/
3.7 is not installed; attempting download
Downloading archive: https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/14.04/x86_64/python-3.7.tar.bz2
$ curl -sSf -o python-3.7.tar.bz2 ${archive_url}
curl: (22) The requested URL returned error: 403 Forbidden
Unable to download 3.7 archive. The archive may not exist. Please consider a different version.
```

I assume, Python 3.7 is not available for this Ubuntu version. You can change your `.travis.yml` file and add `dist: xenial`, this should help.

If I try to download Python 3.7 with `wget`, I get:

```console
$ wget https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/16.04/x86_64/python-3.7.tar.bz2
--2019-03-24 15:52:52--  https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/16.04/x86_64/python-3.7.tar.bz2
Auflösen des Hostnamens s3.amazonaws.com (s3.amazonaws.com)… 52.216.169.229
Verbindungsaufbau zu s3.amazonaws.com (s3.amazonaws.com)|52.216.169.229|:443 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 200 OK
Länge: 65857925 (63M) [application/x-tar]
Wird in »python-3.7.tar.bz2« gespeichert.

python-3.7.tar.bz2                   10%[=====>                                                            ]   6,58M  3,76MB/s
```

**Comment by scls19fr** [comment]
Superseded by #133

**Pull request closed without merging**
