### PR TITLE
Allow bumping of major, minor, and patch version parts.

### PR DESCRIPTION
**Pull request by wtcross**
- allow bumping major, minor, and patch parts
- ignore prerelease and build extensions if present
- added format_version function

### CODE REVIEW

**Comment by k-bx** [comment]
@wtcross thanks!

**Comment by wtcross** [comment]
Thanks for the quick merge. I just realized that I forgot to bump the version :)

**Comment by wtcross** [comment]
How ironic, this is a version bumping library! :smile:

**Comment by k-bx** [comment]
@wtcross haha :) no problem, I bumped it. It's on PyPi now.

**Pull request merged**
