### PR TITLE
Refactor tests: Migrate to py.test and tox

### PR DESCRIPTION
**Pull request by bittner**
* Fix flake8 complaints in semver and setup
* Add tox configuration, use py.test for testing
* Also test Python 3.5
* Remove MANIFEST file (no need for version control)
* Integrate tox in Travis-CI configuration
* Rename tests module (/tests/semver_test.py -> /tests.py)
* Migrate tests from unittest to py.test
* Ensure Python 3.2 support with tox
* Include README.rst (instead of README.md) for PyPI
* Add Contribute section to README
* Move package meta information into module
* PyPI classifiers: Don't state we're useful only for Django
* Add clean command to setup.py

### CODE REVIEW

**Comment by bittner** [comment]
Phew! Python 3.2 and virtualenv via tox, a pain. -- I will now merge the new README into the PR.

**Comment by bittner** [comment]
I've rebased the original commits. We're ready to roll now. Thanks for merging in advance!

**Comment by k-bx** [comment]
@bittner thank you for the contribution, it's highly appreciated. Released under 2.4.2 version.

**Comment by bittner** [comment]
Awesome! That's great!  :+1:

**Pull request merged**
