### PR TITLE
Add support for dot in patch part and major.minor version only

### PR DESCRIPTION
**Pull request by minhkiller**
Add support for "." in patch and major.minor version only.
For example: 1.0, 3.4.5.Final, 4.2.5.RELEASE

### CODE REVIEW

**Comment by minhkiller** [comment]
Hi @k-bx,

I created the PR to support "." in patch and version with major.minor only
For example: 1.0, 3.4.5.Final (hibernate library), 4.2.5.RELEASE (Spring framework)

Could you please help review and consider to merge this upstream?

Thanks,
Minh Tran

**Comment by k-bx** [comment]
@minhkiller thanks for the work, but unfortunately I think I can't merge this. Semver clearly states that PATCH version is an integer, and only allows hyphen to follow it.

I suggest either adding some pre-filtering function which would transform hibernate and sprint-like version into a form which is a valid semver and use this library on top, or to write a complete parser, whatever fits your use-case best.

Thank you for the effort anyways!

**Comment by minhkiller** [comment]
@k-bx Thanks for your response.
Can you accept a lenient mode for the parser? Certainly I'm happy with rejecting shitty version strings by default

**Comment by k-bx** [comment]
@minhkiller actually, yeah, why not. Please make a separate function `parse_lanient` or similar name and make a clear documentation for it, I see no problem having it in-place.

**Comment by minhkiller** [comment]
Cool thanks @k-bx. I will update the PR

**Pull request closed without merging**
