### PR TITLE
Add comparision between VersionInfo objects

### PR DESCRIPTION
**Pull request by ppkt**
I updated `VersionInfo` class to inherit from named tuple and I added rich comparison methods to allow compare between two `VersionInfo` instances or between `VersionInfo` and dictionary.
This PR should resolve issue #54.

Since we are still supporting Python 2.6 it was not possible to use [functools.total_ordering](https://docs.python.org/3.6/library/functools.html#functools.total_ordering).

### CODE REVIEW

**Comment by k-bx** [comment]
Thank you! I'm not sure I understand the error for python2.6, will check it out and merge then. PR looks good

**Comment by ppkt** [comment]
For me it looks like problem with Python interpreter:  [ERROR: InterpreterNotFound: python2.6
](https://travis-ci.org/k-bx/python-semver/jobs/234168946#L194)

Unfortunately I also wasn't able to install Py2.6 on my local machine to test my changes (using pyenv).

**Comment by k-bx** [comment]
So, tests fail on master same way, probably travis updated their image and now it doesn't have 2.6 interpreter there. Anyways, I'll create a separate ticket to handle that, merging meanwhile.

**Comment by k-bx** [comment]
Released under 2.7.7

**Pull request merged**
